services:
  - type: web
    name: golf-team-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
